# Generated by Django 4.0.3 on 2022-03-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orphan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='image',
            field=models.ImageField(default='Members/user.png', upload_to='Orphan/'),
        ),
    ]
