# Generated by Django 3.1.4 on 2022-03-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220323_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_1', models.CharField(max_length=255)),
                ('attribute_1_count', models.IntegerField()),
                ('attribute_1_image', models.ImageField(upload_to='CountriesData/', verbose_name='Attribute 1 Image (66x55)')),
                ('attribute_2', models.CharField(max_length=255)),
                ('attribute_2_count', models.IntegerField()),
                ('attribute_2_image', models.ImageField(upload_to='CountriesData/', verbose_name='Attribute 2 Image (66x55)')),
                ('attribute_3', models.CharField(max_length=255)),
                ('attribute_3_count', models.IntegerField()),
                ('attribute_3_image', models.ImageField(upload_to='CountriesData/', verbose_name='Attribute 3 Image (66x55)')),
                ('attribute_4', models.CharField(max_length=255)),
                ('attribute_4_count', models.IntegerField()),
                ('attribute_4_image', models.ImageField(upload_to='CountriesData/', verbose_name='Attribute 4 Image (66x55)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region')),
            ],
            options={
                'verbose_name_plural': 'Countries Data',
            },
        ),
    ]
