# Generated by Django 3.1.4 on 2022-03-28 10:15

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220328_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='service_image',
            field=models.FileField(upload_to='Hero/', validators=[api.validators.validate_file_extension]),
        ),
    ]
