# Generated by Django 3.1.4 on 2022-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220328_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='video_link',
            new_name='video_link_code',
        ),
    ]
