# Generated by Django 3.1.4 on 2022-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_donationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='fundraiseup_code',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
