# Generated by Django 3.1.4 on 2022-03-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_donationform_fundraiseup_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationform',
            name='milestone',
        ),
    ]
