# Generated by Django 3.1.4 on 2022-03-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_donationform_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationform',
            name='hidden_message',
            field=models.CharField(default='hidden', max_length=999),
            preserve_default=False,
        ),
    ]
