# Generated by Django 4.0.3 on 2022-03-30 07:51

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_aboutus_id_alter_award_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='mainImg',
            field=models.FileField(default='Program/default.jpg', upload_to='Program/', validators=[api.validators.validate_file_extension]),
        ),
    ]
