# Generated by Django 4.0.3 on 2022-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_program_mainimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='region',
        ),
        migrations.AddField(
            model_name='program',
            name='region',
            field=models.ManyToManyField(to='api.region'),
        ),
    ]
