# Generated by Django 4.0.3 on 2022-03-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_program_region_program_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='region',
        ),
        migrations.AddField(
            model_name='program',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.region'),
            preserve_default=False,
        ),
    ]
