# Generated by Django 4.0.3 on 2022-03-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_program_region_program_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='ProgramVideo',
            new_name='ServiceVideo',
        ),
        migrations.RenameField(
            model_name='servicevideo',
            old_name='program',
            new_name='service',
        ),
    ]
