# Generated by Django 4.0.3 on 2022-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_program_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthProgramsOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Menta Health Programs Offered',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Program/')),
                ('video_youtube_link', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RahmaAcademyProgramsOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
            ],
            options={
                'verbose_name_plural': 'Rahma Academy Programs Offered',
            },
        ),
    ]
