# Generated by Django 4.0.3 on 2022-03-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_mentalhealthprogramsoffered_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='region',
        ),
        migrations.AddField(
            model_name='service',
            name='region',
            field=models.ManyToManyField(to='api.region'),
        ),
    ]
